export enum ActionTypes {
  GET_PLANETS = "@@movies/GET_PLANETS",
  GET_PLANETS_SUCCESS = "@@movies/GET_PLANETS_SUCCESS",
  GET_PLANETS_ERROR = "@@movies/GET_PLANETS_ERROR",
  GET_PEOPLE = "@@movies/GET_PEOPLE",
  GET_PEOPLE_SUCCESS = "@@movies/GET_PEOPLE_SUCCESS",
  GET_PEOPLE_ERROR = "@@movies/GET_PEOPLE_ERROR",
  GET_FILMS = "@@movies/GET_FILMS",
  GET_FILMS_SUCCESS = "@@movies/GET_FILMS_SUCCESS",
  GET_FILMS_ERROR = "@@movies/GET_FILMS_ERROR",
  SAVE_PATHNAME = "@@movies/SAVE_PATHNAME",
}
